/**
 * Minimum account balance of microAlgos on Algorand.
 */
export const ALGO_MIN_ACCOUNT_BALANCE = 100000;

export const ALGORAND_ZERO_ADDRESS_STRING =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ";
